In [2]:
import numpy as np
import os
import cv2

In [3]:
labels=['violent','non_violent']
path = "C:/Users/NBH/Desktop/raw/dataset/train/10_FPS/30x30/"
# for label in labels:
#     vector=[]

#     images = [path + label + '/' + wavfile for wavfile in os.listdir(path + '/' + label)]
#     for image in images:
#         img=cv2.imread(image,0)
#         #print(img)
#         vector.append(img)
#     vector = np.asarray(vector)
#     np.save(label + '.npy', vector)


In [11]:
X_train = np.load('C:/Users/NBH/Desktop/raw/dataset/train/10_FPS/30x30/'+labels[0] + '.npy')
y_train = np.zeros(X_train.shape[0])

In [16]:
X_train.shape

array([0., 0., 0., ..., 0., 0., 0.])

In [17]:
for i, label in enumerate(labels[1:]):
    x = np.load('C:/Users/NBH/Desktop/raw/dataset/train/10_FPS/30x30/'+label + '.npy')
    X_train = np.vstack((X_train, x))
    y_train = np.append(y_train, np.full(x.shape[0], fill_value= (i + 1)))

In [20]:
X_train.shape


(26745, 30, 30)

In [5]:
path = "C:/Users/NBH/Desktop/raw/dataset/test/10_FPS/"
for label in labels:
    vector=[]

    images = [path + label + '/' + wavfile for wavfile in os.listdir(path + '/' + label)]
    for image in images:
        img=cv2.imread(image,0)
#         print(img)
        vector.append(img)
    vector = np.asarray(vector)
    np.save(label + '.npy', vector)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[1 0 0 ... 1 1 1]
 [0 0 0 ... 2 2 1]
 [1 0 0 ... 1 1 1]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 1 2 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 2 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[1 1 0 ... 0 0 1]
 [2 2 1 ... 3 3 4]
 [3 3 2 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 2 1]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[5 5 5 ... 0 0 0]
 [6 5 5 ... 1 1 1]
 [6 5 4 ... 0 0 0]
 ...
 [1 1 2 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [2 2 1 ... 1 1 1]]
[[2 2 3 ... 0 0 1]
 [0 1 1 ... 0 0 1]
 [

[[0 0 0 ... 2 1 1]
 [1 1 1 ... 2 2 2]
 [0 0 0 ... 2 2 2]
 ...
 [0 0 0 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]]
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 4 4 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 4 4 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [4 4 4 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [3 4 4 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 3 3 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [2 2 1 ... 1 1 1]]
[[0 0 0 ... 1 1 0]
 [3 2 2 ... 2 2 1]
 [0 0 0 ... 4 5 5]
 ...
 [4 4 4 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [2 2 2 ... 1 1 0]
 [

[[3 3 3 ... 0 0 0]
 [4 3 3 ... 0 0 0]
 [5 5 5 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [2 2 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]]
[[3 3 3 ... 0 0 0]
 [4 3 3 ... 0 0 0]
 [5 5 5 ... 0 0 0]
 ...
 [0 0 0 ... 2 2 2]
 [2 2 2 ... 0 0 0]
 [0 0 0 ... 1 1 1]]
[[3 5 6 ... 0 0 0]
 [3 4 5 ... 1 0 0]
 [4 5 6 ... 1 1 1]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[4 5 4 ... 0 0 0]
 [2 3 3 ... 1 1 1]
 [0 0 1 ... 1 1 1]
 ...
 [1 2 2 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 1 1]]
[[3 4 4 ... 0 0 0]
 [1 2 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[3 2 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [3 3 3 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [2 2 2 ... 1 1 1]]
[[11 12  8 ...  0  0  0]
 [ 3  4  2 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  1  1]
 [ 0  0  0 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]]
[[1 1 2 ... 0 0 0]
 [0 1 2 ... 0 0 0]
 [1 4 6 ... 0 0 0]
 ...
 [3 3 3 ... 1 1 1]
 [1 1 1 ... 2 2 2]
 [2 2 2 ... 0 0 0]]
[[1 

[[244 244 243 ... 243 243 243]
 [244 244 243 ... 243 243 243]
 [244 244 243 ... 243 243 243]
 ...
 [231 230 230 ... 194 194 194]
 [231 230 230 ... 194 194 194]
 [231 230 230 ... 194 194 194]]
[[244 244 243 ... 243 243 243]
 [244 244 243 ... 243 243 243]
 [244 244 243 ... 243 243 243]
 ...
 [231 230 230 ... 196 196 196]
 [231 230 230 ... 196 196 196]
 [231 230 230 ... 198 198 198]]
[[244 244 243 ... 237 237 237]
 [244 244 243 ... 237 237 237]
 [244 244 243 ... 237 237 237]
 ...
 [231 230 230 ... 200 200 200]
 [231 230 230 ... 200 200 200]
 [231 230 230 ... 200 200 200]]
[[210 210 210 ... 233 233 233]
 [210 210 210 ... 233 233 233]
 [210 210 210 ... 233 233 233]
 ...
 [235 235 234 ... 203 203 203]
 [235 235 234 ... 203 203 203]
 [235 235 234 ... 203 203 203]]
[[210 210 210 ... 235 235 235]
 [210 210 210 ... 235 235 235]
 [210 210 210 ... 235 235 235]
 ...
 [221 221 221 ... 208 208 208]
 [223 223 223 ... 208 208 208]
 [226 226 226 ... 208 208 208]]
[[224 224 224 ... 238 238 238]
 [223 223

 [222 222 222 ... 221 214 211]]
[[243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 ...
 [223 223 223 ... 108 109 109]
 [223 223 223 ... 109 108 108]
 [223 223 223 ... 109 109 108]]
[[243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 ...
 [223 223 223 ... 109 109 109]
 [223 223 223 ... 110 109 109]
 [223 223 223 ... 110 109 109]]
[[243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 ...
 [223 223 223 ... 110 110 110]
 [223 223 223 ... 110 110 110]
 [223 223 223 ... 110 110 110]]
[[243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 ...
 [223 223 223 ... 131 129 127]
 [223 223 223 ... 129 127 125]
 [223 223 223 ... 127 125 123]]
[[243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 [243 243 243 ... 243 243 243]
 ...
 [223 223 223 ... 131 134 135]
 [223 223 223 ... 131 134 135]
 [223 223 223 ... 131 134 135]]
[[243 24

[[242 242 242 ... 243 243 243]
 [242 242 242 ... 243 243 243]
 [242 242 242 ... 243 243 243]
 ...
 [160 160 160 ...  79  78  78]
 [160 160 160 ...  78  78  77]
 [160 160 160 ...  78  77  77]]
[[242 242 242 ... 243 243 243]
 [242 242 242 ... 243 243 243]
 [242 242 242 ... 243 243 243]
 ...
 [158 158 158 ...  71  71  70]
 [158 158 158 ...  71  71  70]
 [159 159 159 ...  71  71  70]]
[[242 242 242 ... 244 244 244]
 [242 242 242 ... 244 244 244]
 [242 242 242 ... 244 244 244]
 ...
 [154 156 159 ...  68  68  68]
 [161 162 164 ...  68  68  68]
 [164 166 167 ...  68  68  68]]
[[242 242 242 ... 244 244 244]
 [242 242 242 ... 244 244 244]
 [242 242 242 ... 244 244 244]
 ...
 [153 153 153 ...  93  96  95]
 [160 160 160 ...  83  85  86]
 [165 165 165 ...  80  83  84]]
[[242 242 242 ... 243 243 243]
 [242 242 242 ... 243 243 243]
 [242 242 242 ... 243 243 243]
 ...
 [156 156 156 ... 137 131 128]
 [157 157 157 ... 151 145 142]
 [159 159 159 ... 160 155 151]]
[[242 242 242 ... 243 243 243]
 [242 242

[[ 53  53  53 ... 252 252 252]
 [ 53  53  53 ... 252 252 252]
 [ 52  52  52 ... 252 252 252]
 ...
 [ 19  19  19 ...  39  39  39]
 [ 19  19  19 ...  39  39  39]
 [ 19  19  19 ...  38  39  39]]
[[182 183 184 ... 252 252 252]
 [158 158 158 ... 252 252 252]
 [134 133 132 ... 252 252 252]
 ...
 [ 31  31  31 ...  53  54  54]
 [ 31  31  31 ...  53  54  54]
 [ 31  31  31 ...  53  54  55]]
[[182 183 184 ... 252 252 252]
 [158 158 158 ... 252 252 252]
 [134 133 132 ... 252 252 252]
 ...
 [ 31  31  31 ...  54  54  54]
 [ 31  31  31 ...  54  54  54]
 [ 31  31  31 ...  54  54  54]]
[[224 224 224 ... 248 248 248]
 [223 223 223 ... 248 248 248]
 [225 225 225 ... 248 248 248]
 ...
 [ 25  25  25 ...  11  11  11]
 [ 25  25  25 ...  11  11  11]
 [ 25  25  25 ...  11  11  11]]
[[224 224 224 ... 248 248 248]
 [223 223 223 ... 248 248 248]
 [225 225 225 ... 248 248 248]
 ...
 [ 25  25  25 ...  11  11  11]
 [ 25  25  25 ...  11  11  11]
 [ 25  25  25 ...  11  11  11]]
[[235 235 235 ... 253 253 253]
 [235 235

[[212 212 213 ... 253 253 253]
 [213 214 214 ... 253 253 253]
 [216 216 216 ... 253 253 253]
 ...
 [ 89  89  89 ...  23  23  23]
 [ 89  89  89 ...  23  23  23]
 [ 89  89  89 ...  23  23  23]]
[[234 234 235 ... 252 252 252]
 [234 234 235 ... 252 252 252]
 [234 234 235 ... 252 252 252]
 ...
 [ 97  97  97 ...  19  19  19]
 [ 96  96  96 ...  19  19  19]
 [ 96  96  96 ...  21  21  21]]
[[235 235 235 ... 252 252 252]
 [235 235 235 ... 252 252 252]
 [235 235 235 ... 252 252 252]
 ...
 [ 90  90  90 ...  16  16  16]
 [ 90  90  90 ...  16  16  16]
 [ 90  90  90 ...  16  16  16]]
[[235 235 235 ... 252 252 252]
 [235 235 235 ... 252 252 252]
 [235 235 235 ... 252 252 252]
 ...
 [ 90  90  90 ...  16  16  16]
 [ 90  90  90 ...  16  16  16]
 [ 90  90  90 ...  16  16  16]]
[[228 228 228 ... 252 252 252]
 [228 228 228 ... 252 252 252]
 [228 228 228 ... 252 252 252]
 ...
 [ 84  84  84 ...   9   9   9]
 [ 84  84  84 ...   9   9   9]
 [ 84  84  84 ...   9   9   9]]
[[228 228 228 ... 252 252 252]
 [228 228

[[115 113 112 ... 241 243 241]
 [113 114 114 ... 243 244 242]
 [116 120 122 ... 244 244 242]
 ...
 [ 70  74  81 ... 107 105 103]
 [ 74  78  85 ... 102  99  97]
 [ 75  80  88 ... 100  96  94]]
[[110 115 117 ... 115 113 112]
 [115 119 122 ... 116 114 113]
 [119 123 128 ... 117 115 114]
 ...
 [ 61  61  61 ... 111 111 111]
 [ 61  61  62 ... 111 111 111]
 [ 63  63  63 ... 111 111 111]]
[[110 115 117 ... 116 114 113]
 [115 119 122 ... 117 115 114]
 [119 123 128 ... 118 116 115]
 ...
 [ 61  61  61 ... 111 111 111]
 [ 61  61  62 ... 111 111 111]
 [ 63  63  63 ... 111 111 111]]
[[ 97 100 108 ...  91  91  90]
 [ 97 101 108 ...  90  89  88]
 [ 97 101 108 ...  88  87  86]
 ...
 [ 79  79  79 ... 116 116 116]
 [ 79  79  79 ... 114 114 114]
 [ 79  79  79 ... 115 115 115]]
[[ 97 100 108 ...  91  91  90]
 [ 97 101 108 ...  90  89  88]
 [ 97 101 108 ...  88  87  86]
 ...
 [ 79  79  79 ... 116 116 116]
 [ 79  79  79 ... 114 114 114]
 [ 79  79  79 ... 115 115 115]]
[[ 97 100 108 ...  91  91  90]
 [ 97 101

[[ 40  40  40 ...  99  99  99]
 [ 40  40  40 ...  98  98  98]
 [ 39  39  39 ...  97  97  97]
 ...
 [213 213 213 ... 187 187 187]
 [212 212 213 ... 185 185 185]
 [212 212 212 ... 185 185 185]]
[[ 40  40  40 ...  99  99  99]
 [ 40  40  40 ...  98  98  98]
 [ 39  39  39 ...  97  97  97]
 ...
 [213 213 213 ... 187 187 187]
 [212 212 212 ... 185 185 185]
 [213 212 211 ... 185 185 185]]
[[ 40  40  40 ...  99  99  99]
 [ 40  40  40 ...  98  98  98]
 [ 39  39  39 ...  97  97  97]
 ...
 [213 213 213 ... 187 187 187]
 [212 212 212 ... 185 185 185]
 [213 212 211 ... 185 185 185]]
[[ 54  54  55 ...  95  95  95]
 [ 54  54  54 ...  95  95  95]
 [ 54  54  54 ...  95  95  95]
 ...
 [101 101 101 ... 155 155 155]
 [101 101 101 ... 155 155 155]
 [101 101 101 ... 155 155 155]]
[[ 54  54  55 ...  95  95  95]
 [ 54  54  54 ...  95  95  95]
 [ 54  54  54 ...  95  95  95]
 ...
 [101 101 101 ... 155 155 156]
 [101 101 101 ... 155 155 156]
 [101 101 101 ... 155 155 156]]
[[ 52  52  52 ... 113 117 119]
 [ 52  52

[[1 1 2 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [4 3 3 ... 2 2 2]
 [1 1 0 ... 0 0 0]
 [2 2 1 ... 1 1 1]]
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]]
[[1 1 1 ... 2 2 3]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 1 1 1]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 2 2 2]
 ...
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 0 0 0]
 [2 2 2 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 2 1 1]
 ...
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 2 2 2]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [3 2 2 ... 2 2 2]
 [2 2 2 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [9 9 9 ... 2 2 2]
 [3 3 3 ... 0 0 0]
 [2 2 2 ... 1 1 1]]
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [

[[1 1 1 ... 0 0 0]
 [1 1 1 ... 2 1 1]
 [1 2 2 ... 0 0 0]
 ...
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[2 2 2 ... 0 0 0]
 [0 0 1 ... 2 1 1]
 [2 2 2 ... 0 0 0]
 ...
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 0 1 ... 0 0 0]
 [2 1 1 ... 1 1 1]
 [0 0 1 ... 0 0 0]
 ...
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[2 2 3 ... 0 0 0]
 [2 2 2 ... 2 1 1]
 [1 3 4 ... 0 0 0]
 ...
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[ 1  2  0 ...  2  2  2]
 [ 0  1  0 ...  1  1  1]
 [ 3 10 10 ...  4  4  4]
 ...
 [ 2  2  2 ...  0  0  0]
 [ 1  1  1 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[[0 0 0 ... 2 2 2]
 [2 2 2 ... 1 1 1]
 [0 1 1 ... 4 4 4]
 ...
 [2 2 2 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 0 0 ... 3 2 2]
 [1 1 2 ... 0 0 0]
 [0 1 2 ... 5 5 5]
 ...
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 3 2 2]
 [2 2 2 ... 1 0 0]
 [0 0 0 ... 4 4 4]
 ...
 [2 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[3 

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]]
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 ...
 [4 3 3 ... 0 0 0]
 [0 0 0 ... 5 5 5]
 [1 0 0 ... 3 3 3]]
[[1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 1 1 1]
 ...
 [4 3 3 ... 0 0 0]
 [1 0 0 ... 5 5 6]
 [1 1 0 ... 3 3 3]]
[[2 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 ...
 [2 1 1 ... 3 3 3]
 [1 0 0 ... 1 1 1]
 [0 0 0 ... 2 2 2]]
[[0 0 0 ... 2 2 2]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 4 4 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [2 2 2 ... 1 1 1]]
[[0 0 1 ... 2 2 2]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 2 2 2]
 ...
 [0 0 0 ... 4 4 4]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[0 0 0 ... 2 2 2]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 2 2 2]
 ...
 [2 1 0 ... 2 2 2]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 2 2 2]
 [

[[2 2 3 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [3 3 3 ... 0 0 0]
 ...
 [1 1 1 ... 1 1 0]
 [0 0 0 ... 2 2 1]
 [1 1 1 ... 2 2 2]]
[[0 0 0 ... 2 2 2]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 2 2 2]
 ...
 [2 2 3 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 3 3 3]
 ...
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 3 3 3]
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 5 5 5]
 ...
 [1 1 1 ... 4 4 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 2 2 1]]
[[0 0 0 ... 1 1 0]
 [0 0 0 ... 2 3 3]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 4 4 4]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 2 2 2]]
[[0 0 0 ... 2 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 1 2 2]
 ...
 [1 1 1 ... 5 5 4]
 [0 0 0 ... 3 2 2]
 [0 0 0 ... 3 2 2]]
[[1 1 1 ... 1 1 0]
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 2 3 3]
 [0 0 0 ... 1 2 2]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 2 2 2]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 7 8 9]
 [0 0 0 ... 4 5 6]
 [0 0 0 ... 4 4 4]]
[[2 1 1 ... 3 3 3]
 [0 0 0 ... 2 1 1]
 [

[[191 191 191 ... 140 139 139]
 [191 191 191 ... 140 140 139]
 [191 191 191 ... 141 140 139]
 ...
 [167 167 167 ... 178 178 178]
 [167 167 167 ... 178 178 178]
 [167 167 167 ... 178 178 178]]
[[215 214 216 ... 211 214 223]
 [215 215 216 ... 214 214 219]
 [216 215 215 ... 209 206 207]
 ...
 [167 167 167 ... 178 178 178]
 [167 167 167 ... 178 178 178]
 [167 167 167 ... 178 178 178]]
[[191 191 191 ... 238 239 241]
 [191 191 191 ... 240 242 245]
 [191 191 191 ... 241 244 246]
 ...
 [170 170 170 ... 174 174 174]
 [170 170 170 ... 174 174 174]
 [170 170 170 ... 174 174 174]]
[[251 250 250 ... 178 185 187]
 [251 250 250 ... 180 184 185]
 [251 251 251 ... 179 181 179]
 ...
 [171 171 171 ... 139 136 135]
 [171 171 171 ... 139 136 135]
 [171 171 171 ... 139 136 135]]
[[187 187 187 ...  90  90  90]
 [187 187 187 ...  89  89  89]
 [187 187 187 ...  89  89  89]
 ...
 [172 172 172 ...  86  86  85]
 [172 172 172 ...  86  86  85]
 [172 172 172 ...  86  86  85]]
[[136 136 136 ... 102 102 101]
 [136 136

[[156 156 156 ... 221 222 222]
 [156 155 156 ... 220 221 221]
 [156 155 156 ... 220 220 220]
 ...
 [165 165 165 ... 165 165 165]
 [165 165 165 ... 165 165 165]
 [166 166 166 ... 166 166 166]]
[[221 222 225 ... 132 132 132]
 [221 222 224 ... 132 132 132]
 [221 222 224 ... 132 132 132]
 ...
 [ 29  29  29 ... 138 138 138]
 [ 29  29  29 ... 138 138 138]
 [ 30  30  30 ... 138 138 138]]
[[252 251 252 ... 132 132 132]
 [251 251 251 ... 132 132 132]
 [247 247 246 ... 132 132 132]
 ...
 [ 30  30  30 ... 136 136 136]
 [ 30  30  30 ... 136 136 136]
 [ 30  30  30 ... 136 136 136]]
[[252 251 252 ... 132 132 132]
 [251 251 251 ... 132 132 132]
 [247 247 246 ... 132 132 132]
 ...
 [ 30  30  30 ... 136 136 136]
 [ 30  30  30 ... 136 136 136]
 [ 30  30  30 ... 136 136 136]]
[[252 254 253 ... 132 132 132]
 [255 255 253 ... 132 131 132]
 [254 253 252 ... 132 132 132]
 ...
 [ 30  30  30 ... 139 139 139]
 [ 30  30  30 ... 139 139 139]
 [ 30  30  30 ... 139 139 139]]
[[191 192 195 ... 135 135 135]
 [196 196

 [170 170 170 ... 167 167 167]]
[[127 127 127 ... 143 144 146]
 [127 127 128 ... 152 153 156]
 [128 128 128 ... 161 163 167]
 ...
 [171 171 171 ...  64  64  64]
 [171 171 171 ...  64  64  64]
 [171 171 171 ...  64  64  64]]
[[154 156 157 ... 217 217 217]
 [154 156 157 ... 217 217 217]
 [155 156 157 ... 217 217 217]
 ...
 [163 163 163 ... 159 159 159]
 [163 163 163 ... 159 159 159]
 [163 162 162 ... 160 160 160]]
[[130 130 131 ...  85  85  85]
 [132 133 133 ...  85  85  85]
 [135 135 136 ...  85  85  85]
 ...
 [170 170 170 ...  81  80  80]
 [170 170 170 ...  81  80  80]
 [170 170 170 ...  81  80  80]]
[[142 143 143 ...  84  84  84]
 [141 141 142 ...  84  84  84]
 [139 140 141 ...  84  84  84]
 ...
 [169 169 169 ... 110 104 101]
 [169 169 168 ... 109 103 100]
 [169 169 168 ... 109 103 100]]
[[126 126 127 ...  88  88  88]
 [125 125 126 ...  88  88  88]
 [125 124 125 ...  88  88  88]
 ...
 [167 167 167 ... 169 169 169]
 [167 167 167 ... 169 169 169]
 [167 167 167 ... 169 169 169]]
[[128 12

[[ 93  93  93 ... 106 106 106]
 [ 93  93  93 ... 108 108 108]
 [ 93  93  93 ... 111 111 111]
 ...
 [143 143 144 ... 161 162 162]
 [144 144 144 ... 160 161 161]
 [144 145 145 ... 161 163 163]]
[[ 92  92  91 ... 106 106 106]
 [ 92  92  91 ... 107 107 107]
 [ 92  92  91 ... 109 109 109]
 ...
 [142 142 142 ... 224 224 224]
 [142 142 142 ... 223 223 223]
 [142 142 142 ... 222 222 222]]
[[ 92  92  91 ... 106 106 106]
 [ 92  92  91 ... 107 107 107]
 [ 92  92  91 ... 109 109 109]
 ...
 [142 142 142 ... 222 222 222]
 [142 142 142 ... 222 222 222]
 [142 142 142 ... 222 222 222]]
[[ 92  92  91 ... 106 106 106]
 [ 92  92  91 ... 107 107 107]
 [ 92  92  91 ... 107 107 107]
 ...
 [142 142 142 ...  79  79  78]
 [142 142 142 ...  79  79  78]
 [142 142 142 ...  79  79  78]]
[[ 93  93  93 ... 105 105 105]
 [ 93  93  93 ... 105 105 105]
 [ 93  93  93 ... 105 105 105]
 ...
 [144 144 144 ... 215 215 215]
 [144 144 144 ... 222 222 222]
 [144 144 144 ... 226 226 226]]
[[ 93  93  93 ... 107 107 107]
 [ 93  93

[[144 144 144 ...  99 102 117]
 [144 144 144 ...  86  88 101]
 [146 146 146 ...  89  87  84]
 ...
 [166 166 166 ... 151 151 151]
 [166 166 166 ... 152 151 151]
 [166 166 166 ... 153 152 151]]
[[164 165 165 ...  88  89  90]
 [162 164 163 ...  88  89  90]
 [160 162 162 ...  88  89  90]
 ...
 [177 176 176 ... 181 184 186]
 [182 182 182 ... 181 183 186]
 [182 182 182 ... 180 182 185]]
[[152 155 158 ... 131 130 129]
 [148 151 154 ... 125 124 122]
 [143 147 151 ... 121 120 118]
 ...
 [156 158 160 ... 216 200 188]
 [162 163 165 ... 206 199 188]
 [165 166 167 ... 201 200 188]]
[[144 143 141 ... 139 142 144]
 [147 146 143 ... 142 145 147]
 [147 146 144 ... 145 148 150]
 ...
 [150 150 150 ... 227 235 237]
 [150 150 150 ... 225 236 239]
 [150 150 150 ... 220 235 240]]
[[111 111 111 ... 107 116 118]
 [112 112 112 ... 107 115 117]
 [113 113 113 ... 107 114 116]
 ...
 [148 148 150 ... 209 209 209]
 [147 148 149 ... 211 210 210]
 [146 147 149 ... 210 211 211]]
[[111 111 111 ... 115 114 114]
 [111 111

[[ 81  81  82 ... 142 137 135]
 [ 83  84  84 ... 142 137 135]
 [ 87  87  87 ... 142 137 135]
 ...
 [159 159 159 ... 145 145 145]
 [159 159 159 ... 145 145 145]
 [159 159 159 ... 145 145 145]]
[[111 111 110 ... 103 105 105]
 [110 110 110 ...  96  96  96]
 [109 109 109 ...  90  90  89]
 ...
 [165 165 165 ...  63  63  63]
 [165 165 165 ...  63  63  63]
 [165 165 165 ...  63  63  63]]
[[ 81  81  82 ... 141 137 135]
 [ 83  84  84 ... 141 137 135]
 [ 87  87  87 ... 141 137 135]
 ...
 [159 159 159 ... 145 145 145]
 [159 159 159 ... 145 145 145]
 [159 159 159 ... 145 145 145]]
[[ 88  96 105 ...  68  68  68]
 [ 89  97 105 ...  70  70  70]
 [ 88  95 104 ...  71  71  71]
 ...
 [159 159 159 ... 145 145 145]
 [159 159 159 ... 145 145 145]
 [159 159 159 ... 145 145 145]]
[[ 96  96  96 ...  71  71  71]
 [ 96  96  96 ...  71  71  71]
 [ 95  95  95 ...  71  71  71]
 ...
 [159 159 159 ... 136 136 136]
 [159 159 159 ... 136 136 136]
 [159 159 159 ... 136 136 136]]
[[ 82  82  82 ...  71  69  70]
 [ 82  82

[[108 108 108 ... 254 254 254]
 [108 108 108 ... 254 254 254]
 [107 107 107 ... 254 254 254]
 ...
 [167 167 167 ... 102 102 102]
 [167 167 167 ... 102 102 102]
 [167 167 167 ... 102 102 102]]
[[109 109 109 ... 156 156 156]
 [109 109 109 ... 156 156 156]
 [109 109 109 ... 156 156 156]
 ...
 [ 75  75  75 ... 102 102 102]
 [ 75  75  75 ... 102 102 102]
 [ 75  75  75 ... 102 102 102]]
[[111 111 111 ... 156 156 156]
 [111 111 111 ... 156 156 156]
 [111 111 111 ... 156 156 156]
 ...
 [150 150 150 ... 102 102 102]
 [150 150 150 ... 102 102 102]
 [150 150 150 ... 102 102 102]]
[[ 94  94  94 ... 158 158 158]
 [ 94  94  94 ... 158 158 158]
 [ 94  94  94 ... 158 158 158]
 ...
 [107 107 108 ... 109 109 109]
 [107 107 108 ... 109 109 109]
 [107 107 108 ... 109 109 109]]
[[109 109 110 ...  93  92  92]
 [109 110 110 ...  93  92  92]
 [109 110 110 ...  93  92  92]
 ...
 [205 205 205 ... 153 153 153]
 [205 205 205 ... 153 153 153]
 [205 205 205 ... 154 154 154]]
[[105 105 105 ...  87  87  87]
 [104 104

[[114 114 114 ... 114 112 109]
 [114 114 114 ... 115 114 110]
 [114 114 114 ... 116 114 111]
 ...
 [202 202 202 ... 155 155 155]
 [201 201 201 ... 155 155 155]
 [201 201 201 ... 155 155 155]]
[[115 115 115 ... 123 122 121]
 [115 115 115 ... 122 121 121]
 [115 115 115 ... 122 122 121]
 ...
 [201 201 201 ... 155 155 155]
 [201 201 201 ... 155 155 155]
 [201 201 201 ... 155 155 155]]
[[115 115 115 ... 117 117 117]
 [115 115 115 ... 117 117 117]
 [115 115 115 ... 117 117 117]
 ...
 [208 208 208 ... 160 160 160]
 [210 209 209 ... 160 160 160]
 [211 211 211 ... 160 160 160]]
[[115 115 115 ... 108 108 108]
 [115 115 115 ... 108 108 108]
 [115 115 115 ... 108 108 108]
 ...
 [173 173 173 ... 168 168 168]
 [173 173 173 ... 169 169 169]
 [173 173 173 ... 169 169 169]]
[[123 122 121 ... 109 110 110]
 [123 123 122 ... 109 109 110]
 [124 124 123 ... 109 109 109]
 ...
 [173 173 173 ... 156 156 156]
 [173 173 173 ... 156 156 156]
 [173 173 173 ... 156 156 156]]
[[129 129 129 ... 122 118 116]
 [128 128

[[150 150 149 ... 113 120 122]
 [150 150 149 ... 113 120 122]
 [150 150 149 ... 113 120 122]
 ...
 [170 170 170 ... 171 171 171]
 [170 170 170 ... 171 171 171]
 [170 170 170 ... 171 171 171]]
[[150 150 149 ...  96  96  96]
 [150 150 149 ...  96  96  96]
 [150 150 149 ...  96  96  96]
 ...
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]]
[[150 150 149 ...  97  96  96]
 [150 150 149 ...  97  96  96]
 [150 150 149 ...  97  96  96]
 ...
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]]
[[151 151 151 ... 130 129 127]
 [151 151 151 ... 128 127 125]
 [151 151 151 ... 126 124 122]
 ...
 [171 171 171 ... 173 173 173]
 [171 171 171 ... 173 173 173]
 [171 171 171 ... 173 173 173]]
[[150 149 149 ... 109 109 109]
 [150 149 149 ... 108 108 108]
 [150 149 149 ... 106 106 105]
 ...
 [171 171 171 ... 177 177 177]
 [171 171 171 ... 177 177 177]
 [171 171 171 ... 177 177 177]]
[[143 143 143 ... 150 149 148]
 [143 143

[[ 92  92  92 ... 144 144 144]
 [ 92  92  92 ... 144 144 144]
 [ 92  92  92 ... 144 144 144]
 ...
 [199 199 198 ... 173 173 173]
 [200 199 198 ... 173 173 173]
 [201 201 200 ... 173 173 173]]
[[ 92  92  92 ... 143 143 143]
 [ 92  92  92 ... 143 143 143]
 [ 92  92  92 ... 143 143 143]
 ...
 [209 208 208 ... 174 174 174]
 [208 208 208 ... 174 174 174]
 [209 209 209 ... 174 174 174]]
[[ 92  92  92 ... 144 144 144]
 [ 92  92  92 ... 144 144 144]
 [ 92  92  92 ... 144 144 144]
 ...
 [202 201 201 ... 103 102 101]
 [201 201 200 ... 103 102 101]
 [201 201 200 ... 103 102 101]]
[[115 115 114 ... 156 156 156]
 [115 115 114 ... 156 156 156]
 [115 115 114 ... 156 156 156]
 ...
 [169 169 169 ... 102 102 102]
 [169 169 169 ... 102 102 102]
 [169 169 169 ... 102 102 102]]
[[ 99  98  98 ... 146 146 146]
 [ 99  98  98 ... 146 146 146]
 [ 99  98  98 ... 146 146 146]
 ...
 [203 201 198 ... 102 102 102]
 [206 203 200 ... 102 102 102]
 [208 206 203 ... 102 102 102]]
[[ 97  97  97 ... 152 151 151]
 [ 97  97

[[ 94  94  94 ...  95  94  92]
 [ 94  94  94 ...  95  93  92]
 [ 93  93  93 ...  94  93  91]
 ...
 [171 171 171 ... 102 102 102]
 [171 171 171 ... 102 102 102]
 [171 171 171 ... 102 102 102]]
[[105 105 105 ... 122 106  97]
 [105 105 105 ... 122 106  97]
 [105 105 105 ... 122 106  97]
 ...
 [166 166 166 ... 102 102 102]
 [166 166 166 ... 102 102 102]
 [166 166 166 ... 102 102 102]]
[[105 105 105 ... 122 106  97]
 [105 105 105 ... 122 106  97]
 [105 105 105 ... 121 106  97]
 ...
 [166 166 166 ... 102 102 102]
 [166 166 166 ... 102 102 102]
 [166 166 166 ... 102 102 102]]
[[105 105 105 ... 159 159 159]
 [105 105 105 ... 159 159 159]
 [105 105 105 ... 159 159 159]
 ...
 [163 163 163 ... 111 110 110]
 [163 163 163 ... 118 118 118]
 [163 163 163 ... 123 122 122]]
[[105 105 105 ... 100 100 100]
 [105 105 105 ... 100 101 101]
 [105 105 105 ... 101 101 101]
 ...
 [165 165 165 ... 107 107 107]
 [165 165 165 ... 107 107 107]
 [165 165 165 ... 108 108 108]]
[[105 105 105 ...  99  99  99]
 [105 105

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

MemoryError: 

In [ ]:
test_violent = np.load('')